version: "3.7"
services:

  test_assignment:
    build:
      dockerfile: ./Dockerfile
      context: ./
    restart: always
    links:
      - postgres
    depends_on:
      - postgres
    ports:
      - "8081:8081"

  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "mydb"
      POSTGRES_USER: "myuser"
      POSTGRES_PASSWORD: "secret"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./build/compose/db/init:/docker-entrypoint-initdb.d
      - ..:/var/lib/postgresql/data
    expose: 
      - "5432"  
    ports:
      - "5432:5432"